# Generated by Django 3.2.5 on 2021-08-30 13:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('forname', models.CharField(max_length=50, null=True, verbose_name='Prénom')),
            ],
            options={
                'verbose_name': 'auteur',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'catégorie',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('type', models.CharField(choices=[('Vente', 'Vente'), ('Arrivage', 'Arrivage')], default='', max_length=10, verbose_name='Type')),
                ('reference', models.BigIntegerField(blank=True, null=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('auteurs', models.CharField(max_length=400, verbose_name='Auteurs')),
                ('editeurs', models.CharField(max_length=200, verbose_name='Editeur')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Prix')),
                ('catPrice', models.CharField(choices=[('SELIO', 'SELIO'), ('Editeur', 'Editeur'), ('Dépôt', 'Dépôt'), ('Occasion', 'Occasion')], default='SELIO', max_length=10, verbose_name='CatPrice')),
                ('payment', models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Carte', 'Carte')], default='Espèces', max_length=10, verbose_name='Payment')),
                ('fournisseur', models.CharField(default='', max_length=50, verbose_name='Fournisseur')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('comment', models.CharField(blank=True, default='', max_length=10, verbose_name='Commentaire')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('marge', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Marge')),
            ],
            options={
                'verbose_name': 'éditeur',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.BigIntegerField(blank=True, null=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('publication', models.IntegerField(blank=True, null=True, verbose_name='Parution')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Prix')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='couv/')),
                ('note', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Note')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('auteurs', models.ManyToManyField(related_name='ouvrages', to='store.Author')),
                ('categories', models.ManyToManyField(related_name='ouvrages', to='store.Categorie')),
                ('editeurs', models.ManyToManyField(related_name='ouvrages', to='store.Publisher')),
            ],
            options={
                'verbose_name': 'ouvrage',
            },
        ),
    ]
