# Generated by Django 3.2.5 on 2021-09-13 10:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MR', 'Monsieur'), ('MISS', 'Mademoiselle'), ('MRS', 'Madame')], default='MR', max_length=4, verbose_name='Civilité')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom')),
                ('company', models.CharField(blank=True, max_length=50, verbose_name='Société')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('additional_address', models.CharField(blank=True, max_length=255, verbose_name="Complément d'adresse")),
                ('postcode', models.CharField(max_length=5, verbose_name='Code postal')),
                ('city', models.CharField(max_length=50, verbose_name='Ville')),
                ('phone', models.CharField(max_length=10, verbose_name='Téléphone')),
                ('mobilephone', models.CharField(blank=True, max_length=10, verbose_name='Téléphone portable')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('forname', models.CharField(max_length=50, null=True, verbose_name='Prénom')),
            ],
            options={
                'verbose_name': 'auteur',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('W', 'En attente de validation'), ('K', 'Contacté'), ('P', 'Payée'), ('S', 'Expédiée'), ('C', 'Annulée'), ('D', 'Annulé')], max_length=1, null=True, verbose_name='Statut de la commande')),
            ],
            options={
                'verbose_name': 'réservation',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'catégorie',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('type', models.CharField(choices=[('Vente', 'Vente'), ('Arrivage', 'Arrivage')], default='', max_length=10, verbose_name='Type')),
                ('reference', models.BigIntegerField(blank=True, null=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('auteurs', models.CharField(max_length=400, verbose_name='Auteurs')),
                ('editeurs', models.CharField(max_length=200, verbose_name='Editeur')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Prix')),
                ('catPrice', models.CharField(choices=[('SELIO', 'SELIO'), ('Editeur', 'Editeur'), ('Dépôt', 'Dépôt'), ('Occasion', 'Occasion')], default='SELIO', max_length=10, verbose_name='CatPrice')),
                ('payment', models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Carte', 'Carte')], default='Espèces', max_length=10, verbose_name='Payment')),
                ('fournisseur', models.CharField(default='', max_length=50, verbose_name='Fournisseur')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('comment', models.CharField(blank=True, default='', max_length=10, verbose_name='Commentaire')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('marge', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Marge')),
            ],
            options={
                'verbose_name': 'éditeur',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.BigIntegerField(blank=True, null=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('publication', models.IntegerField(blank=True, null=True, verbose_name='Parution')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Prix')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='couv/')),
                ('note', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Note')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('auteurs', models.ManyToManyField(related_name='ouvrages', to='store.Author')),
                ('categories', models.ManyToManyField(related_name='ouvrages', to='store.Categorie')),
                ('editeurs', models.ManyToManyField(related_name='ouvrages', to='store.Publisher')),
            ],
            options={
                'verbose_name': 'ouvrage',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_invoicing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_invoicing_address', to='store.address', verbose_name='Adresse de facturation par défaut')),
                ('default_shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_shipping_address', to='store.address', verbose_name='Adresse de livraison par défaut')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Contact')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='Quantité')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.booking', verbose_name='Commande associée')),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.ouvrage')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.contact'),
        ),
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.contact'),
        ),
    ]
