# Generated by Django 3.2.5 on 2021-07-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='forname',
            field=models.CharField(max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='marge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Marge'),
        ),
    ]
