# Generated by Django 3.2.5 on 2021-07-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210711_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrage',
            name='auteurs',
            field=models.ManyToManyField(related_name='ouvrages', to='store.Author'),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='ouvrages', to='store.Categorie'),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='editeurs',
            field=models.ManyToManyField(related_name='ouvrages', to='store.Publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='marge',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Marge'),
        ),
    ]
