# Generated by Django 3.2.5 on 2021-09-03 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contacted',
        ),
    ]
