# Generated by Django 3.2.5 on 2021-07-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='forname',
            field=models.CharField(max_length=50, null=True, verbose_name='Prénom'),
        ),
    ]
