# Generated by Django 3.2.5 on 2021-09-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_booking_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
