# Generated by Django 3.2.5 on 2021-07-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_author_forname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrage',
            name='reference',
            field=models.BigIntegerField(null=True, verbose_name='Référence'),
        ),
    ]
