# Generated by Django 3.2.5 on 2021-07-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_ouvrage_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrage',
            name='note',
            field=models.CharField(max_length=1000, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='picture',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='publication',
            field=models.IntegerField(null=True, verbose_name='Parution'),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Parution'),
        ),
    ]
