# Generated by Django 3.2.5 on 2021-07-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210711_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Prix'),
        ),
    ]
