# Generated by Django 3.2.5 on 2021-09-30 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210930_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='default_invoicing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_invoicing_address', to='store.address', verbose_name='Adresse de facturation'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='default_shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_shipping_address', to='store.address', verbose_name='Adresse de livraison'),
        ),
    ]
