# Generated by Django 3.2.5 on 2021-07-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_ouvrage_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouvrage',
            name='picture',
        ),
    ]
