# Generated by Django 3.2.5 on 2021-07-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_ouvrage_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrage',
            name='picture',
            field=models.FilePathField(null=True),
        ),
    ]
