# Generated by Django 3.2.5 on 2021-07-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='ouvrages',
        ),
        migrations.AddField(
            model_name='vente',
            name='catPrice',
            field=models.CharField(choices=[('SELIO', 'SELIO'), ('Editeur', 'Editeur'), ('Dépôt', 'Dépôt'), ('Occasion', 'Occasion')], default='SELIO', max_length=10, verbose_name='catPrice'),
        ),
        migrations.AddField(
            model_name='vente',
            name='ouvrage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.ouvrage'),
        ),
        migrations.AddField(
            model_name='vente',
            name='payment',
            field=models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Carte', 'Carte')], default='Espèces', max_length=10, verbose_name='payment'),
        ),
    ]
