# Generated by Django 3.2.5 on 2021-07-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_ouvrage_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrage',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
