# Generated by Django 3.2.5 on 2021-07-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_ouvrage_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrage',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='publication',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parution'),
        ),
        migrations.AlterField(
            model_name='ouvrage',
            name='reference',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Référence'),
        ),
    ]
