# Generated by Django 3.2.5 on 2021-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20210726_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
