# Generated by Django 3.2.5 on 2021-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_vente_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.BigIntegerField(blank=True, null=True, verbose_name='Référence')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('auteurs', models.CharField(max_length=400, verbose_name='Auteurs')),
                ('editeurs', models.CharField(max_length=200, verbose_name='Editeur')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Prix')),
                ('catPrice', models.CharField(max_length=10, verbose_name='CatPrix')),
                ('payment', models.CharField(max_length=10, verbose_name='Paiement')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('date', models.DateField(verbose_name='Date')),
                ('comment', models.CharField(max_length=10, verbose_name='Commentaire')),
            ],
        ),
    ]
