# Generated by Django 3.2.5 on 2021-07-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_ouvrage_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrage',
            name='note',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Note'),
        ),
    ]
