# Generated by Django 3.2.5 on 2021-07-30 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_vente_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
