# Generated by Django 3.2.5 on 2021-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='catPrice',
            field=models.CharField(choices=[('SELIO', 'SELIO'), ('Editeur', 'Editeur'), ('Dépôt', 'Dépôt'), ('Occasion', 'Occasion')], default='SELIO', max_length=10, verbose_name='catPrice'),
        ),
        migrations.AlterField(
            model_name='history',
            name='payment',
            field=models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Carte', 'Carte')], default='Espèces', max_length=10, verbose_name='payment'),
        ),
    ]
