# Generated by Django 3.2.5 on 2021-07-30 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20210730_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='fournisseur',
            field=models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Carte', 'Carte')], default='', max_length=50, verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='history',
            name='type',
            field=models.CharField(choices=[('Vente', 'Vente'), ('Arrivage', 'Arrivage')], default='', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='history',
            name='catPrice',
            field=models.CharField(choices=[('SELIO', 'SELIO'), ('Editeur', 'Editeur'), ('Dépôt', 'Dépôt'), ('Occasion', 'Occasion')], default='SELIO', max_length=10, verbose_name='CatPrice'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='history',
            name='payment',
            field=models.CharField(choices=[('Espèces', 'Espèces'), ('Chèque', 'Chèque'), ('Carte', 'Carte')], default='Espèces', max_length=10, verbose_name='Payment'),
        ),
    ]
