# Generated by Django 3.2.5 on 2021-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_delete_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='fournisseur',
            field=models.CharField(default='', max_length=50, verbose_name='Fournisseur'),
        ),
    ]
