# Generated by Django 3.2.5 on 2021-07-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_history_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Commentaire'),
        ),
    ]
